import { ListingStatus, TackleCategory, TackleCondition, WaterType } from '@prisma/client';

export type ListingSeedInput = {
  brand: string;
  baseTitle: string;
  modelName: string;
  description: string;
  tackleCategory: TackleCategory;
  waterType?: WaterType;
  lureStyle?: string;
  targetSpecies: string[];
  techniqueTags: string[];
  seasonalUse: string[];
  lineRating?: { min: number; max: number };
  rodPower?: string;
  rodAction?: string;
  gearRatio?: string;
  bearingCount?: number;
  lengthIn?: number;
  weightOz?: number;
  maxDragLb?: number;
  shippingProfileKey: string;
  featuredAsset: string;
  gallery: string[];
  aiNotes: string;
  price: number;
};

export type ListingSeedVariant = {
  suffix: string;
  condition: TackleCondition;
  priceMultiplier: number;
  status: ListingStatus;
  provenance: string;
};

const VARIANTS: ListingSeedVariant[] = [
  {
    suffix: '',
    condition: TackleCondition.NEW_IN_BOX,
    priceMultiplier: 1,
    status: ListingStatus.ACTIVE,
    provenance: 'Vision QA 2024-06 • Supplier manifest cross-check',
  },
  {
    suffix: ' - Demo Fleet',
    condition: TackleCondition.EXCELLENT,
    priceMultiplier: 0.92,
    status: ListingStatus.ACTIVE,
    provenance: 'Guide program inspection • Boat sensor log 2024 spring',
  },
  {
    suffix: ' - Guide Service Retired',
    condition: TackleCondition.GOOD,
    priceMultiplier: 0.84,
    status: ListingStatus.ACTIVE,
    provenance: 'Dock intake photos • AI abrasion score 0.18',
  },
  {
    suffix: ' - Photo Draft',
    condition: TackleCondition.LIKE_NEW,
    priceMultiplier: 0.9,
    status: ListingStatus.DRAFT,
    provenance: 'AI draft awaiting seller approval • Manual copy pending',
  },
];

export const BASE_PRODUCTS: ListingSeedInput[] = [
  {
    brand: 'Shimano',
    baseTitle: 'Shimano Antares DC Casting Reel',
    modelName: 'Antares DC 2024 XG',
    description:
      'Flagship JDM casting reel featuring digitally controlled braking and a cold-forged MagnumLite spool for ultra-smooth casting.',
    tackleCategory: TackleCategory.REEL,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Largemouth Bass', 'Smallmouth Bass'],
    techniqueTags: ['Jigs', 'Topwater', 'Jerkbaits'],
    seasonalUse: ['Spring', 'Summer', 'Fall'],
    gearRatio: '8.5:1',
    bearingCount: 11,
    weightOz: 6.2,
    maxDragLb: 11,
    shippingProfileKey: 'reel-box',
    featuredAsset: '/seed-images/reel-lowprofile.svg',
    gallery: ['/seed-images/reel-lowprofile.svg', '/seed-images/storage-tackle-tray.svg'],
    aiNotes: 'AI tuned description cross-checked with Shimano global spec sheet.',
    price: 599,
  },
  {
    brand: 'Daiwa',
    baseTitle: 'Daiwa Steez A II Casting Reel',
    modelName: 'Steez A II 100H',
    description:
      'Fully aluminum Steez A platform with HyperDrive gearing and Hyper Armed housing for power fishing durability.',
    tackleCategory: TackleCategory.REEL,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Largemouth Bass', 'Striped Bass'],
    techniqueTags: ['Swimbaits', 'Frogging'],
    seasonalUse: ['Summer', 'Fall'],
    gearRatio: '7.1:1',
    bearingCount: 12,
    weightOz: 6.7,
    maxDragLb: 13,
    shippingProfileKey: 'reel-box',
    featuredAsset: '/seed-images/reel-lowprofile.svg',
    gallery: ['/seed-images/reel-lowprofile.svg', '/seed-images/rod-heavy-cover.svg'],
    aiNotes: 'QA matched to Daiwa HyperDrive torque documentation.',
    price: 549,
  },
  {
    brand: 'Abu Garcia',
    baseTitle: 'Abu Garcia Revo STX LP Reel',
    modelName: 'Revo STX Gen 5',
    description:
      'Carbon Matrix drag system and IVCB-6 braking deliver confident performance for reaction baits and finesse jigs alike.',
    tackleCategory: TackleCategory.REEL,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Bass', 'Walleye'],
    techniqueTags: ['Bladed Jigs', 'Swim Jigs'],
    seasonalUse: ['Spring', 'Summer'],
    gearRatio: '7.3:1',
    bearingCount: 10,
    weightOz: 7.4,
    maxDragLb: 24,
    shippingProfileKey: 'reel-box',
    featuredAsset: '/seed-images/reel-lowprofile.svg',
    gallery: ['/seed-images/reel-lowprofile.svg', '/seed-images/lure-crankbait.svg'],
    aiNotes: 'Verified against Pure Fishing service manual torque specs.',
    price: 269,
  },
  {
    brand: "Lew's",
    baseTitle: "Lew's Pro-Ti SLP Casting Reel",
    modelName: 'Pro-Ti SLP 7.5:1',
    description:
      'Low-profile magnesium frame reel tuned for aggressive casting with a 95mm carbon handle and Winn Dri-Tac knobs.',
    tackleCategory: TackleCategory.REEL,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Bass', 'Snakehead'],
    techniqueTags: ['Pitching', 'Skipping'],
    seasonalUse: ['Spring', 'Summer'],
    gearRatio: '7.5:1',
    bearingCount: 11,
    weightOz: 5.8,
    maxDragLb: 20,
    shippingProfileKey: 'reel-box',
    featuredAsset: '/seed-images/reel-lowprofile.svg',
    gallery: ['/seed-images/reel-lowprofile.svg', '/seed-images/lure-swimbait.svg'],
    aiNotes: 'Spec sheet imported from Lew’s tournament support team.',
    price: 349,
  },
  {
    brand: 'Okuma',
    baseTitle: 'Okuma Hakai DT Casting Reel',
    modelName: 'Hakai DT 7.1:1',
    description:
      'Featherweight magnesium frame with Flite Drive spool hub and titanium main gear for offshore structure work.',
    tackleCategory: TackleCategory.REEL,
    waterType: WaterType.BRACKISH,
    targetSpecies: ['Spotted Bass', 'Redfish'],
    techniqueTags: ['Inshore', 'Swimbaits'],
    seasonalUse: ['Spring', 'Fall'],
    gearRatio: '7.1:1',
    bearingCount: 10,
    weightOz: 6,
    maxDragLb: 20,
    shippingProfileKey: 'reel-box',
    featuredAsset: '/seed-images/reel-lowprofile.svg',
    gallery: ['/seed-images/reel-lowprofile.svg', '/seed-images/boat-shallow-anchor.svg'],
    aiNotes: 'Hybrid saltwater/freshwater compliance review complete.',
    price: 299,
  },
  {
    brand: '13 Fishing',
    baseTitle: '13 Fishing Concept C2 Reel',
    modelName: 'Concept C2 8.3:1',
    description:
      'Generation 2 Concept platform with Arrowhead line guide and low-inertia spool for skipping docks and finesse power fishing.',
    tackleCategory: TackleCategory.REEL,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Bass'],
    techniqueTags: ['Dock Skipping', 'Finesse Jigs'],
    seasonalUse: ['Summer', 'Fall'],
    gearRatio: '8.3:1',
    bearingCount: 9,
    weightOz: 6,
    maxDragLb: 25,
    shippingProfileKey: 'reel-box',
    featuredAsset: '/seed-images/reel-lowprofile.svg',
    gallery: ['/seed-images/reel-lowprofile.svg', '/seed-images/rod-finesse.svg'],
    aiNotes: 'AI summary matched to 13 Fishing engineering bulletins.',
    price: 230,
  },
  {
    brand: 'KastKing',
    baseTitle: 'KastKing MegaJaws Elite Reel',
    modelName: 'MegaJaws Elite 7.2:1',
    description:
      'Elite series low-profile reel featuring Digigear brass drive and AutoMag dual braking for long casts with heavier baits.',
    tackleCategory: TackleCategory.REEL,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Bass', 'Musky'],
    techniqueTags: ['A-Rig', 'Swimbaits'],
    seasonalUse: ['Winter', 'Spring'],
    gearRatio: '7.2:1',
    bearingCount: 11,
    weightOz: 6.9,
    maxDragLb: 17,
    shippingProfileKey: 'reel-box',
    featuredAsset: '/seed-images/reel-lowprofile.svg',
    gallery: ['/seed-images/reel-lowprofile.svg', '/seed-images/lure-swimbait.svg'],
    aiNotes: 'Cross-checked with KastKing Elite product release forms.',
    price: 229,
  },
  {
    brand: 'Penn',
    baseTitle: 'Penn Slammer IV Spinning Reel',
    modelName: 'Slammer IV 3500 DX',
    description:
      'IPX6 sealed CNC gear spinning reel ideal for inshore saltwater or heavy freshwater duty with Dura-Drag washers.',
    tackleCategory: TackleCategory.REEL,
    waterType: WaterType.SALTWATER,
    targetSpecies: ['Striped Bass', 'Snook'],
    techniqueTags: ['Inshore', 'Jetty'],
    seasonalUse: ['Spring', 'Summer'],
    gearRatio: '6.2:1',
    bearingCount: 9,
    weightOz: 12,
    maxDragLb: 30,
    shippingProfileKey: 'reel-box',
    featuredAsset: '/seed-images/reel-spinning.svg',
    gallery: ['/seed-images/reel-spinning.svg', '/seed-images/lure-swimbait.svg'],
    aiNotes: 'Saltwater corrosion checklist verified with Penn service team.',
    price: 279,
  },
  {
    brand: 'Quantum',
    baseTitle: 'Quantum Smoke S3 Spinning Reel',
    modelName: 'Smoke S3 30',
    description:
      'PT anti-corrosion bearings and hot sauce lubrication tuned for finesse smallmouth presentations.',
    tackleCategory: TackleCategory.REEL,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Smallmouth Bass', 'Trout'],
    techniqueTags: ['Drop Shot', 'Ned Rig'],
    seasonalUse: ['Spring', 'Summer'],
    gearRatio: '6.0:1',
    bearingCount: 11,
    weightOz: 8.5,
    maxDragLb: 18,
    shippingProfileKey: 'reel-box',
    featuredAsset: '/seed-images/reel-spinning.svg',
    gallery: ['/seed-images/reel-spinning.svg', '/seed-images/rod-finesse.svg'],
    aiNotes: 'Calibrated against Quantum pro staff finesse setups.',
    price: 199,
  },
  {
    brand: 'Shimano',
    baseTitle: 'Shimano Vanford Spinning Reel',
    modelName: 'Vanford 2500HGF',
    description:
      'CI4+ frame, MagnumLite rotor, and MicroModule II gearing deliver a buttery-smooth finesse spinning experience.',
    tackleCategory: TackleCategory.REEL,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Spotted Bass', 'Trout'],
    techniqueTags: ['Finesse', 'Dropshot'],
    seasonalUse: ['Spring', 'Winter'],
    gearRatio: '6.0:1',
    bearingCount: 9,
    weightOz: 6.3,
    maxDragLb: 20,
    shippingProfileKey: 'reel-box',
    featuredAsset: '/seed-images/reel-spinning.svg',
    gallery: ['/seed-images/reel-spinning.svg', '/seed-images/lure-crankbait.svg'],
    aiNotes: 'Matched with Shimano Japan parts catalog for accuracy.',
    price: 249,
  },
  {
    brand: 'G. Loomis',
    baseTitle: 'G. Loomis NRX+ JWR Casting Rod',
    modelName: 'NRX+ 893C JWR',
    description:
      'Next generation NRX+ blank tuned for bottom-contact sensitivity with Hybrid Guide train and new Mega Modulus+ graphite.',
    tackleCategory: TackleCategory.ROD,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Largemouth Bass'],
    techniqueTags: ['Jigs', 'Texas Rig'],
    seasonalUse: ['Spring', 'Fall'],
    lineRating: { min: 12, max: 16 },
    rodPower: 'Medium Heavy',
    rodAction: 'Extra Fast',
    lengthIn: 89,
    weightOz: 3.9,
    shippingProfileKey: 'rod-tube',
    featuredAsset: '/seed-images/rod-heavy-cover.svg',
    gallery: ['/seed-images/rod-heavy-cover.svg', '/seed-images/reel-lowprofile.svg'],
    aiNotes: 'Blank geometry confirmed with G. Loomis service schematics.',
    price: 625,
  },
  {
    brand: 'St. Croix',
    baseTitle: 'St. Croix Legend Xtreme Casting Rod',
    modelName: 'Legend Xtreme 7\'4" H',
    description:
      'SCVI and SCV carbon hybrid blank with Fuji Titanium guides for grass mat frog applications and punching setups.',
    tackleCategory: TackleCategory.ROD,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Bass'],
    techniqueTags: ['Frogging', 'Punching'],
    seasonalUse: ['Summer'],
    lineRating: { min: 50, max: 65 },
    rodPower: 'Heavy',
    rodAction: 'Fast',
    lengthIn: 88,
    weightOz: 4.5,
    shippingProfileKey: 'rod-tube',
    featuredAsset: '/seed-images/rod-heavy-cover.svg',
    gallery: ['/seed-images/rod-heavy-cover.svg', '/seed-images/combo-frog.svg'],
    aiNotes: 'St. Croix lab bending curve overlay attached in provenance memo.',
    price: 429,
  },
  {
    brand: 'Dobyns',
    baseTitle: 'Dobyns Champion XP 736C',
    modelName: 'Champion XP DC736C',
    description:
      'Versatile heavy cover rod beloved for frogging and close-quarters pitching with Kevlar wrapping reinforcement.',
    tackleCategory: TackleCategory.ROD,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Bass'],
    techniqueTags: ['Frogging', 'Pitching'],
    seasonalUse: ['Summer', 'Fall'],
    lineRating: { min: 15, max: 30 },
    rodPower: 'Heavy',
    rodAction: 'Fast',
    lengthIn: 87,
    weightOz: 4.4,
    shippingProfileKey: 'rod-tube',
    featuredAsset: '/seed-images/rod-heavy-cover.svg',
    gallery: ['/seed-images/rod-heavy-cover.svg', '/seed-images/lure-swimbait.svg'],
    aiNotes: 'Dobyns QC sheet scanned to confirm guide placements.',
    price: 259,
  },
  {
    brand: 'Megabass',
    baseTitle: 'Megabass Destroyer P5 Dark Sleeper Rod',
    modelName: 'Destroyer P5 Dark Sleeper',
    description:
      'Japan-built Destroyer platform tuned for bottom-contact swimbait presentations with Kaiju casting seat.',
    tackleCategory: TackleCategory.ROD,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Bass'],
    techniqueTags: ['Swimbaits', 'Dragging'],
    seasonalUse: ['Spring', 'Fall'],
    lineRating: { min: 10, max: 25 },
    rodPower: 'Medium Heavy',
    rodAction: 'Fast',
    lengthIn: 85,
    weightOz: 4.2,
    shippingProfileKey: 'rod-tube',
    featuredAsset: '/seed-images/rod-finesse.svg',
    gallery: ['/seed-images/rod-finesse.svg', '/seed-images/lure-swimbait.svg'],
    aiNotes: 'Megabass US product master referenced for spec lock.',
    price: 499,
  },
  {
    brand: '13 Fishing',
    baseTitle: '13 Fishing Envy Black 7\'3" MH',
    modelName: 'Envy Black 73MH-C',
    description:
      'Evolve custom reel seat and Fuji K guides for a balanced do-everything casting rod covering chatterbaits to light swimbaits.',
    tackleCategory: TackleCategory.ROD,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Bass'],
    techniqueTags: ['Chatterbait', 'Swim Jig'],
    seasonalUse: ['Spring', 'Summer'],
    lineRating: { min: 12, max: 20 },
    rodPower: 'Medium Heavy',
    rodAction: 'Fast',
    lengthIn: 87,
    weightOz: 4,
    shippingProfileKey: 'rod-tube',
    featuredAsset: '/seed-images/rod-finesse.svg',
    gallery: ['/seed-images/rod-finesse.svg', '/seed-images/lure-crankbait.svg'],
    aiNotes: 'Spec verified with 13 Fishing North America warranty team.',
    price: 300,
  },
  {
    brand: 'Shimano',
    baseTitle: 'Shimano Poison Adrena Casting Rod',
    modelName: 'Poison Adrena 7\'2" MH',
    description:
      'Full carbon monocoque handle transfers bottom contact feedback while Hi-Power X blank resists twist.',
    tackleCategory: TackleCategory.ROD,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Bass'],
    techniqueTags: ['Jigs', 'Worms'],
    seasonalUse: ['Spring', 'Fall'],
    lineRating: { min: 10, max: 20 },
    rodPower: 'Medium Heavy',
    rodAction: 'Fast',
    lengthIn: 86,
    weightOz: 4.1,
    shippingProfileKey: 'rod-tube',
    featuredAsset: '/seed-images/rod-finesse.svg',
    gallery: ['/seed-images/rod-finesse.svg', '/seed-images/reel-spinning.svg'],
    aiNotes: 'Shimano JDM spec translation stored with provenance memo.',
    price: 379,
  },
  {
    brand: 'Daiwa',
    baseTitle: 'Daiwa Tatula Elite AGS Rod',
    modelName: 'Tatula Elite AGS 7\'3"',
    description:
      'AGS carbon guides and SVF Nanoplus blank optimized for long-bomb casting and winding presentations.',
    tackleCategory: TackleCategory.ROD,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Bass'],
    techniqueTags: ['Crankbait', 'Swim Jig'],
    seasonalUse: ['Summer', 'Fall'],
    lineRating: { min: 10, max: 20 },
    rodPower: 'Medium Heavy',
    rodAction: 'Fast',
    lengthIn: 87,
    weightOz: 4.3,
    shippingProfileKey: 'rod-tube',
    featuredAsset: '/seed-images/rod-heavy-cover.svg',
    gallery: ['/seed-images/rod-heavy-cover.svg', '/seed-images/lure-crankbait.svg'],
    aiNotes: 'Tatula Elite pro staff tuning sheet attached.',
    price: 299,
  },
  {
    brand: 'Phenix',
    baseTitle: 'Phenix Feather Finesse Rod',
    modelName: 'Feather 7\'1" ML',
    description:
      'Ultra-light Toray T-36 blank with carbon fiber reinforced handle for finesse swimbait and dropshot applications.',
    tackleCategory: TackleCategory.ROD,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Spotted Bass', 'Trout'],
    techniqueTags: ['Dropshot', 'Neko'],
    seasonalUse: ['Spring', 'Winter'],
    lineRating: { min: 4, max: 10 },
    rodPower: 'Medium Light',
    rodAction: 'Extra Fast',
    lengthIn: 85,
    weightOz: 3.1,
    shippingProfileKey: 'rod-tube',
    featuredAsset: '/seed-images/rod-finesse.svg',
    gallery: ['/seed-images/rod-finesse.svg', '/seed-images/reel-spinning.svg'],
    aiNotes: 'Finesse torque modeling data stored with listing metadata.',
    price: 189,
  },
  {
    brand: 'Ark Rods',
    baseTitle: 'Ark Invoker Pro Casting Rod',
    modelName: 'Invoker Pro 7\'6" H',
    description:
      'Ark Reactor blank with double helix reinforcement built for Carolina rigs and offshore structure dragging.',
    tackleCategory: TackleCategory.ROD,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Bass'],
    techniqueTags: ['Carolina Rig', 'Dragging'],
    seasonalUse: ['Summer', 'Fall'],
    lineRating: { min: 12, max: 25 },
    rodPower: 'Heavy',
    rodAction: 'Fast',
    lengthIn: 90,
    weightOz: 4.8,
    shippingProfileKey: 'rod-tube',
    featuredAsset: '/seed-images/rod-heavy-cover.svg',
    gallery: ['/seed-images/rod-heavy-cover.svg', '/seed-images/lure-swimbait.svg'],
    aiNotes: 'Ark lab bend curve photo uploaded to provenance vault.',
    price: 229,
  },
  {
    brand: 'Temple Fork Outfitters',
    baseTitle: 'TFO Tactical Elite Bass Rod',
    modelName: 'Tactical Elite 7\'4" MH',
    description:
      'Lightweight Tactical Elite blank with Fuji K guides for chatterbaits, spinnerbaits, and power finesse tasks.',
    tackleCategory: TackleCategory.ROD,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Bass'],
    techniqueTags: ['Chatterbait', 'Spinnerbait'],
    seasonalUse: ['Spring', 'Summer'],
    lineRating: { min: 10, max: 20 },
    rodPower: 'Medium Heavy',
    rodAction: 'Moderate Fast',
    lengthIn: 88,
    weightOz: 4.5,
    shippingProfileKey: 'rod-tube',
    featuredAsset: '/seed-images/rod-heavy-cover.svg',
    gallery: ['/seed-images/rod-heavy-cover.svg', '/seed-images/lure-crankbait.svg'],
    aiNotes: 'Guide wraps inspected with AI surface analysis for cracks.',
    price: 199,
  },
  {
    brand: 'Shimano',
    baseTitle: 'Shimano Zodias Frog Combo',
    modelName: 'Zodias 7\'2" H + Curado 150 MGL',
    description:
      'Factory-balanced frog combo pairing a heavy Zodias casting rod with the new Curado 150 MGL tuned for braid.',
    tackleCategory: TackleCategory.ROD_AND_REEL_COMBO,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Bass'],
    techniqueTags: ['Frogging', 'Power Fishing'],
    seasonalUse: ['Summer'],
    lineRating: { min: 40, max: 65 },
    rodPower: 'Heavy',
    rodAction: 'Fast',
    gearRatio: '8.1:1',
    bearingCount: 8,
    lengthIn: 86,
    weightOz: 7.8,
    shippingProfileKey: 'combo-case',
    featuredAsset: '/seed-images/combo-frog.svg',
    gallery: ['/seed-images/combo-frog.svg', '/seed-images/rod-heavy-cover.svg'],
    aiNotes: 'Combo balanced in lab, AI validated spool tension settings.',
    price: 469,
  },
  {
    brand: 'Daiwa',
    baseTitle: 'Daiwa Tatula Elite Skipping Combo',
    modelName: 'Tatula Elite AGS 6\'9" + Tatula SV TW103',
    description:
      'Skipping-focused combo featuring a short AGS rod and SV spooled reel for dock target fishing.',
    tackleCategory: TackleCategory.ROD_AND_REEL_COMBO,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Bass'],
    techniqueTags: ['Dock Skipping', 'Wacky'],
    seasonalUse: ['Summer'],
    lineRating: { min: 10, max: 20 },
    rodPower: 'Medium Heavy',
    rodAction: 'Fast',
    gearRatio: '7.1:1',
    bearingCount: 7,
    lengthIn: 81,
    weightOz: 7.5,
    shippingProfileKey: 'combo-case',
    featuredAsset: '/seed-images/combo-frog.svg',
    gallery: ['/seed-images/combo-frog.svg', '/seed-images/rod-finesse.svg'],
    aiNotes: 'Skip training AI recorded spool data for provenance log.',
    price: 399,
  },
  {
    brand: 'Abu Garcia',
    baseTitle: 'Abu Garcia Veritas PLX Combo',
    modelName: "Veritas PLX 7' MH + Revo SX",
    description:
      'Balanced combo for multi-purpose bass fishing with lightweight Powerlux blank and proven Revo SX reel.',
    tackleCategory: TackleCategory.ROD_AND_REEL_COMBO,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Bass'],
    techniqueTags: ['All-Purpose', 'Texas Rig'],
    seasonalUse: ['Spring', 'Summer'],
    lineRating: { min: 10, max: 20 },
    rodPower: 'Medium Heavy',
    rodAction: 'Fast',
    gearRatio: '6.6:1',
    bearingCount: 9,
    lengthIn: 84,
    weightOz: 8.2,
    shippingProfileKey: 'combo-case',
    featuredAsset: '/seed-images/combo-frog.svg',
    gallery: ['/seed-images/combo-frog.svg', '/seed-images/reel-lowprofile.svg'],
    aiNotes: 'Spec cross-checked with Pure Fishing combo builder.',
    price: 329,
  },
  {
    brand: "Lew's",
    baseTitle: "Lew's KVD Topwater Combo",
    modelName: 'KVD 6\'10" M + KVD 200',
    description:
      'Kevin VanDam signature combo for walking baits with a fast tip and responsive aluminum frame reel.',
    tackleCategory: TackleCategory.ROD_AND_REEL_COMBO,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Bass'],
    techniqueTags: ['Topwater', 'Walking Baits'],
    seasonalUse: ['Summer', 'Fall'],
    lineRating: { min: 8, max: 15 },
    rodPower: 'Medium',
    rodAction: 'Fast',
    gearRatio: '7.5:1',
    bearingCount: 10,
    lengthIn: 82,
    weightOz: 7.3,
    shippingProfileKey: 'combo-case',
    featuredAsset: '/seed-images/combo-frog.svg',
    gallery: ['/seed-images/combo-frog.svg', '/seed-images/lure-crankbait.svg'],
    aiNotes: 'Topwater cadence validated with AI audio sync of walk-the-dog.',
    price: 279,
  },
  {
    brand: 'Favorite',
    baseTitle: 'Favorite Big Sexy Combo',
    modelName: 'Big Sexy 7\'3" H + Soleus XCS',
    description:
      'Favorite Fishing combo built for heavy cover flipping with a stout rod and aluminum frame reel.',
    tackleCategory: TackleCategory.ROD_AND_REEL_COMBO,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Bass'],
    techniqueTags: ['Flipping', 'Punching'],
    seasonalUse: ['Summer'],
    lineRating: { min: 20, max: 65 },
    rodPower: 'Heavy',
    rodAction: 'Fast',
    gearRatio: '7.3:1',
    bearingCount: 10,
    lengthIn: 87,
    weightOz: 8.5,
    shippingProfileKey: 'combo-case',
    featuredAsset: '/seed-images/combo-frog.svg',
    gallery: ['/seed-images/combo-frog.svg', '/seed-images/rod-heavy-cover.svg'],
    aiNotes: 'AI abrasion scoring verified EVA grip condition before publishing.',
    price: 249,
  },
  {
    brand: 'Megabass',
    baseTitle: 'Megabass Vision 110+1 Jerkbait',
    modelName: 'Vision 110+1 French Pearl',
    description:
      'Suspending jerkbait tuned for cold water cadence with tungsten multi-way moving balancer system.',
    tackleCategory: TackleCategory.LURE,
    waterType: WaterType.FRESHWATER,
    lureStyle: 'Jerkbait',
    targetSpecies: ['Bass', 'Walleye'],
    techniqueTags: ['Jerkbait', 'Pause Cadence'],
    seasonalUse: ['Winter', 'Spring'],
    shippingProfileKey: 'lure-mailer',
    featuredAsset: '/seed-images/lure-crankbait.svg',
    gallery: ['/seed-images/lure-crankbait.svg', '/seed-images/lure-swimbait.svg'],
    aiNotes: 'Colorway verified against Megabass master swatch.',
    price: 25,
  },
  {
    brand: 'Megabass',
    baseTitle: 'Megabass Magdraft 8" Swimbait',
    modelName: 'Magdraft 8" MB Gizzard',
    description:
      'Magdraft full-size swimbait with harnessed treble and magnet keeper for trophy bass hunts.',
    tackleCategory: TackleCategory.LURE,
    waterType: WaterType.FRESHWATER,
    lureStyle: 'Swimbait',
    targetSpecies: ['Bass', 'Striper'],
    techniqueTags: ['Swimbait', 'Slow Roll'],
    seasonalUse: ['Spring', 'Summer'],
    shippingProfileKey: 'lure-mailer',
    featuredAsset: '/seed-images/lure-swimbait.svg',
    gallery: ['/seed-images/lure-swimbait.svg', '/seed-images/rod-heavy-cover.svg'],
    aiNotes: 'Harness magnets inspected for corrosion before listing.',
    price: 34,
  },
  {
    brand: 'Z-Man',
    baseTitle: 'Z-Man JackHammer 3/8 oz',
    modelName: 'JackHammer Green Pumpkin Shad',
    description:
      'Signature chatterbait co-designed with Evergreen featuring Gamakatsu hook and hand-tied skirting.',
    tackleCategory: TackleCategory.LURE,
    waterType: WaterType.FRESHWATER,
    lureStyle: 'Bladed Jig',
    targetSpecies: ['Bass'],
    techniqueTags: ['Bladed Jig', 'Grass Lines'],
    seasonalUse: ['Spring', 'Fall'],
    shippingProfileKey: 'lure-mailer',
    featuredAsset: '/seed-images/lure-swimbait.svg',
    gallery: ['/seed-images/lure-swimbait.svg', '/seed-images/terminal-jighead.svg'],
    aiNotes: 'Skirt flare captured in AI photo audit for provenance log.',
    price: 18,
  },
  {
    brand: 'Strike King',
    baseTitle: 'Strike King 6XD Crankbait',
    modelName: '6XD Sexy Shad',
    description:
      'Deep diving crankbait reaching 18+ feet with weight transfer for long casts offshore.',
    tackleCategory: TackleCategory.LURE,
    waterType: WaterType.FRESHWATER,
    lureStyle: 'Crankbait',
    targetSpecies: ['Bass'],
    techniqueTags: ['Offshore', 'Cranking'],
    seasonalUse: ['Summer'],
    shippingProfileKey: 'lure-mailer',
    featuredAsset: '/seed-images/lure-crankbait.svg',
    gallery: ['/seed-images/lure-crankbait.svg', '/seed-images/rod-heavy-cover.svg'],
    aiNotes: 'Bill integrity inspected using AI-assisted crack detection.',
    price: 8,
  },
  {
    brand: 'Berkley',
    baseTitle: 'Berkley Stunna 112+1',
    modelName: 'Stunna 112+1 Stealth Shad',
    description:
      'Hank Cherry-designed jerkbait with rolling slow sink action and dual tungsten weight transfer.',
    tackleCategory: TackleCategory.LURE,
    waterType: WaterType.FRESHWATER,
    lureStyle: 'Jerkbait',
    targetSpecies: ['Bass'],
    techniqueTags: ['Jerkbait', 'Cold Water'],
    seasonalUse: ['Winter', 'Spring'],
    shippingProfileKey: 'lure-mailer',
    featuredAsset: '/seed-images/lure-crankbait.svg',
    gallery: ['/seed-images/lure-crankbait.svg', '/seed-images/lure-swimbait.svg'],
    aiNotes: 'Factory hooks swapped for #5 Fusion19 and documented in log.',
    price: 15,
  },
  {
    brand: 'Jackall',
    baseTitle: 'Jackall Kaera Frog',
    modelName: 'Kaera Frog Navy Blue',
    description: 'Compact frog with upward angled hooks and keeled body for skipping under cover.',
    tackleCategory: TackleCategory.LURE,
    waterType: WaterType.FRESHWATER,
    lureStyle: 'Frog',
    targetSpecies: ['Bass'],
    techniqueTags: ['Frogging', 'Skipping'],
    seasonalUse: ['Summer'],
    shippingProfileKey: 'lure-mailer',
    featuredAsset: '/seed-images/lure-swimbait.svg',
    gallery: ['/seed-images/lure-swimbait.svg', '/seed-images/combo-frog.svg'],
    aiNotes: 'Elastomer body softness measured for provenance record.',
    price: 12,
  },
  {
    brand: '6th Sense',
    baseTitle: '6th Sense Crush 100X',
    modelName: 'Crush 100X Shad Scales',
    description:
      'Medium diving squarebill with premium paint and sharp black nickel hooks for power cranking in cover.',
    tackleCategory: TackleCategory.LURE,
    waterType: WaterType.FRESHWATER,
    lureStyle: 'Squarebill',
    targetSpecies: ['Bass'],
    techniqueTags: ['Power Fishing', 'Shallow'],
    seasonalUse: ['Spring', 'Fall'],
    shippingProfileKey: 'lure-mailer',
    featuredAsset: '/seed-images/lure-crankbait.svg',
    gallery: ['/seed-images/lure-crankbait.svg', '/seed-images/rod-heavy-cover.svg'],
    aiNotes: 'QC ensures lips true and hook hangers aligned pre-shipment.',
    price: 9,
  },
  {
    brand: 'SPRO',
    baseTitle: 'SPRO Little John MD',
    modelName: 'Little John MD Blue Gill',
    description:
      'Silent medium diver with tungsten weight transfer for stealthy presentations around pressured fish.',
    tackleCategory: TackleCategory.LURE,
    waterType: WaterType.FRESHWATER,
    lureStyle: 'Crankbait',
    targetSpecies: ['Bass'],
    techniqueTags: ['Cranking', 'Pressured Fish'],
    seasonalUse: ['Fall'],
    shippingProfileKey: 'lure-mailer',
    featuredAsset: '/seed-images/lure-crankbait.svg',
    gallery: ['/seed-images/lure-crankbait.svg', '/seed-images/lure-swimbait.svg'],
    aiNotes: 'Tungsten weight movement recorded via accelerometer bench.',
    price: 10,
  },
  {
    brand: 'Hog Farmer',
    baseTitle: 'Hog Farmer BFL A-Rig',
    modelName: '5-Wire BFL Umbrella',
    description:
      'Tournament-legal 5-wire Alabama rig with titanium arms and screw lock heads for swimbaits.',
    tackleCategory: TackleCategory.LURE,
    waterType: WaterType.FRESHWATER,
    lureStyle: 'Umbrella Rig',
    targetSpecies: ['Bass', 'Striper'],
    techniqueTags: ['Umbrella Rig', 'Cold Water'],
    seasonalUse: ['Winter'],
    shippingProfileKey: 'lure-mailer',
    featuredAsset: '/seed-images/lure-swimbait.svg',
    gallery: ['/seed-images/lure-swimbait.svg', '/seed-images/terminal-jighead.svg'],
    aiNotes: 'Wire angle measurements captured for compliance record.',
    price: 35,
  },
  {
    brand: 'Rapala',
    baseTitle: 'Rapala DT16 Crankbait',
    modelName: 'DT16 Caribbean Shad',
    description:
      'Balsa body deep diver tuned by hand to reach 16 feet with a tight wobble in cold water conditions.',
    tackleCategory: TackleCategory.LURE,
    waterType: WaterType.FRESHWATER,
    lureStyle: 'Crankbait',
    targetSpecies: ['Bass'],
    techniqueTags: ['Offshore', 'Cold Water'],
    seasonalUse: ['Winter', 'Spring'],
    shippingProfileKey: 'lure-mailer',
    featuredAsset: '/seed-images/lure-crankbait.svg',
    gallery: ['/seed-images/lure-crankbait.svg', '/seed-images/rod-heavy-cover.svg'],
    aiNotes: 'Each bait tank tested and serial logged for authenticity.',
    price: 8,
  },
  {
    brand: 'Deps',
    baseTitle: 'Deps Slide Swimmer 250',
    modelName: 'Slide Swimmer 250 Flash Carp',
    description:
      'Soft skin glide bait with ABS core delivering a slow-sink big bait profile for trophy bass.',
    tackleCategory: TackleCategory.LURE,
    waterType: WaterType.FRESHWATER,
    lureStyle: 'Glide Bait',
    targetSpecies: ['Bass'],
    techniqueTags: ['Glide Bait', 'Slow Retrieve'],
    seasonalUse: ['Spring', 'Fall'],
    shippingProfileKey: 'lure-mailer',
    featuredAsset: '/seed-images/lure-swimbait.svg',
    gallery: ['/seed-images/lure-swimbait.svg', '/seed-images/rod-heavy-cover.svg'],
    aiNotes: 'JDM authenticity check with serial photo stored in provenance.',
    price: 169,
  },
  {
    brand: 'Nichols Lures',
    baseTitle: 'Nichols Ben Parker Spoon',
    modelName: '8" Magnum Flutter Spoon',
    description:
      'Magnum flutter spoon stamped in the USA with premium treble and swivel, ideal for summer ledge fishing.',
    tackleCategory: TackleCategory.LURE,
    waterType: WaterType.FRESHWATER,
    lureStyle: 'Spoon',
    targetSpecies: ['Bass'],
    techniqueTags: ['Ledge Fishing', 'Offshore'],
    seasonalUse: ['Summer'],
    shippingProfileKey: 'lure-mailer',
    featuredAsset: '/seed-images/lure-swimbait.svg',
    gallery: ['/seed-images/lure-swimbait.svg', '/seed-images/rod-heavy-cover.svg'],
    aiNotes: 'Weight tolerance measured and logged for QC traceability.',
    price: 18,
  },
  {
    brand: 'Seaguar',
    baseTitle: 'Seaguar Tatsu Fluorocarbon',
    modelName: 'Tatsu 15lb 200 yd',
    description:
      'Double-structure fluorocarbon line offering abrasion resistance and suppleness for clear water presentations.',
    tackleCategory: TackleCategory.LINE,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Bass', 'Walleye'],
    techniqueTags: ['Jigs', 'Leader Material'],
    seasonalUse: ['All'],
    shippingProfileKey: 'line-spool',
    featuredAsset: '/seed-images/line-fluorocarbon.svg',
    gallery: ['/seed-images/line-fluorocarbon.svg', '/seed-images/rod-finesse.svg'],
    aiNotes: 'Spool lot number logged with Seaguar authenticity portal.',
    price: 45,
  },
  {
    brand: 'Sunline',
    baseTitle: 'Sunline Shooter Fluorocarbon',
    modelName: 'Shooter 20lb 165 yd',
    description:
      'High density fluorocarbon designed for flipping and pitching heavy cover with minimal stretch.',
    tackleCategory: TackleCategory.LINE,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Bass'],
    techniqueTags: ['Flipping', 'Pitching'],
    seasonalUse: ['Summer'],
    shippingProfileKey: 'line-spool',
    featuredAsset: '/seed-images/line-fluorocarbon.svg',
    gallery: ['/seed-images/line-fluorocarbon.svg', '/seed-images/rod-heavy-cover.svg'],
    aiNotes: 'Line memory tested with AI-assisted spool inspection camera.',
    price: 42,
  },
  {
    brand: 'PowerPro',
    baseTitle: 'PowerPro Maxcuatro Braid',
    modelName: 'Maxcuatro 50lb 150 yd',
    description:
      'Four-end Spectra braid that is 25% thinner for better casting with frogs and swimbaits in heavy vegetation.',
    tackleCategory: TackleCategory.LINE,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Bass'],
    techniqueTags: ['Frogging', 'Swimbait'],
    seasonalUse: ['Summer'],
    shippingProfileKey: 'line-spool',
    featuredAsset: '/seed-images/line-fluorocarbon.svg',
    gallery: ['/seed-images/line-fluorocarbon.svg', '/seed-images/combo-frog.svg'],
    aiNotes: 'Diameter measured with laser micrometer for provenance note.',
    price: 39,
  },
  {
    brand: 'Sufix',
    baseTitle: 'Sufix 832 Advanced Braid',
    modelName: '832 10lb Ghost',
    description:
      'Eight-carrier braid with GORE Performance fibers for finesse spinning setups needing strong knots.',
    tackleCategory: TackleCategory.LINE,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Bass', 'Trout'],
    techniqueTags: ['Finesse', 'Spinning'],
    seasonalUse: ['All'],
    shippingProfileKey: 'line-spool',
    featuredAsset: '/seed-images/line-fluorocarbon.svg',
    gallery: ['/seed-images/line-fluorocarbon.svg', '/seed-images/rod-finesse.svg'],
    aiNotes: 'Braid colorfast test results logged for support review.',
    price: 31,
  },
  {
    brand: 'Gamakatsu',
    baseTitle: 'Gamakatsu Hybrid Worm Hook',
    modelName: 'Hybrid Worm Hook 4/0',
    description:
      'Hybrid round/extra-wide gap hook for Texas rigs with Nano Smooth Coat finish for easy hooksets.',
    tackleCategory: TackleCategory.TERMINAL_TACKLE,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Bass'],
    techniqueTags: ['Texas Rig', 'Soft Plastics'],
    seasonalUse: ['All'],
    shippingProfileKey: 'terminal-mailer',
    featuredAsset: '/seed-images/terminal-jighead.svg',
    gallery: ['/seed-images/terminal-jighead.svg', '/seed-images/lure-swimbait.svg'],
    aiNotes: 'Hook point sharpness measured and recorded pre-packaging.',
    price: 6,
  },
  {
    brand: 'Owner',
    baseTitle: 'Owner Jungle Flippin Hook',
    modelName: 'Jungle Flippin 5/0',
    description:
      'Heavy-duty flipping hook with welded eye and Zo-Wire construction for punching mats.',
    tackleCategory: TackleCategory.TERMINAL_TACKLE,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Bass'],
    techniqueTags: ['Punching', 'Heavy Cover'],
    seasonalUse: ['Summer'],
    shippingProfileKey: 'terminal-mailer',
    featuredAsset: '/seed-images/terminal-jighead.svg',
    gallery: ['/seed-images/terminal-jighead.svg', '/seed-images/combo-frog.svg'],
    aiNotes: 'Heat treat certification logged with Owner part batch.',
    price: 7,
  },
  {
    brand: 'VMC',
    baseTitle: 'VMC RedLine Neko Hook',
    modelName: 'RedLine Series 2/0',
    description:
      'VMC Neko hook featuring a compressed needle point and sliding keeper for finesse worm rigs.',
    tackleCategory: TackleCategory.TERMINAL_TACKLE,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Bass'],
    techniqueTags: ['Neko Rig', 'Finesse'],
    seasonalUse: ['Spring', 'Fall'],
    shippingProfileKey: 'terminal-mailer',
    featuredAsset: '/seed-images/terminal-jighead.svg',
    gallery: ['/seed-images/terminal-jighead.svg', '/seed-images/rod-finesse.svg'],
    aiNotes: 'Keeper tension measured via AI vision assisted jig test.',
    price: 5,
  },
  {
    brand: 'Garmin',
    baseTitle: 'Garmin LiveScope XR System',
    modelName: 'LiveScope XR LVS62 Bundle',
    description:
      'Extended range live sonar system with GLS 10 black box and XR transducer for offshore scanning.',
    tackleCategory: TackleCategory.ELECTRONICS,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Bass', 'Crappie'],
    techniqueTags: ['Forward Facing Sonar', 'Scouting'],
    seasonalUse: ['All'],
    shippingProfileKey: 'electronics-case',
    featuredAsset: '/seed-images/electronics-sonar.svg',
    gallery: ['/seed-images/electronics-sonar.svg', '/seed-images/boat-shallow-anchor.svg'],
    aiNotes: 'Serial registered with Garmin trade-in ledger for provenance.',
    price: 2999,
  },
  {
    brand: 'Humminbird',
    baseTitle: 'Humminbird Mega Live TargetLock',
    modelName: 'Mega Live TargetLock Ultrex 45"',
    description:
      'TargetLock mount keeps live sonar focused on structure independently from the trolling motor.',
    tackleCategory: TackleCategory.ELECTRONICS,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Bass'],
    techniqueTags: ['Forward Facing Sonar'],
    seasonalUse: ['All'],
    shippingProfileKey: 'electronics-case',
    featuredAsset: '/seed-images/electronics-sonar.svg',
    gallery: ['/seed-images/electronics-sonar.svg', '/seed-images/boat-shallow-anchor.svg'],
    aiNotes: 'Firmware version recorded pre-listing for compliance trace.',
    price: 2999,
  },
  {
    brand: 'Lowrance',
    baseTitle: 'Lowrance ActiveTarget 2',
    modelName: 'ActiveTarget 2 Module & Transducer',
    description:
      'High resolution real-time sonar with Scout Wide, Forward, and Down viewing modes.',
    tackleCategory: TackleCategory.ELECTRONICS,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Bass', 'Crappie'],
    techniqueTags: ['Live Sonar', 'Forward Facing'],
    seasonalUse: ['All'],
    shippingProfileKey: 'electronics-case',
    featuredAsset: '/seed-images/electronics-sonar.svg',
    gallery: ['/seed-images/electronics-sonar.svg', '/seed-images/boat-shallow-anchor.svg'],
    aiNotes: 'Module stress test recorded to minio bucket for audit trail.',
    price: 2749,
  },
  {
    brand: 'Plano',
    baseTitle: 'Plano EDGE Flex 3700',
    modelName: 'EDGE Flex 3700',
    description: 'Customizable tackle tray with EZ Label system, rust-blocker, and 38 dividers.',
    tackleCategory: TackleCategory.STORAGE_AND_ORGANIZATION,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Universal'],
    techniqueTags: ['Storage', 'Organization'],
    seasonalUse: ['All'],
    shippingProfileKey: 'storage-mailer',
    featuredAsset: '/seed-images/storage-tackle-tray.svg',
    gallery: ['/seed-images/storage-tackle-tray.svg', '/seed-images/lure-crankbait.svg'],
    aiNotes: 'Divider layout captured and stored for QA reproducibility.',
    price: 39,
  },
  {
    brand: 'Yeti',
    baseTitle: 'Yeti LoadOut GoBox 30',
    modelName: 'LoadOut GoBox 30 Tan',
    description:
      'Virtually indestructible gear box for boat storage featuring Pack Attic tray and removable divider.',
    tackleCategory: TackleCategory.STORAGE_AND_ORGANIZATION,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Universal'],
    techniqueTags: ['Boat Storage', 'Organization'],
    seasonalUse: ['All'],
    shippingProfileKey: 'storage-mailer',
    featuredAsset: '/seed-images/storage-tackle-tray.svg',
    gallery: ['/seed-images/storage-tackle-tray.svg', '/seed-images/boat-shallow-anchor.svg'],
    aiNotes: 'Interior layout photographed for AI inventory tracking.',
    price: 249,
  },
  {
    brand: 'Minn Kota',
    baseTitle: 'Minn Kota Ultrex Quest 112',
    modelName: 'Ultrex Quest 112 52" 36V',
    description:
      'Next generation Ultrex trolling motor with QUEST brushless technology and target lock integration.',
    tackleCategory: TackleCategory.BOAT_AND_MARINE_ACCESSORY,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Universal'],
    techniqueTags: ['Boat Control', 'Forward Facing Sonar'],
    seasonalUse: ['All'],
    shippingProfileKey: 'boat-crate',
    featuredAsset: '/seed-images/boat-shallow-anchor.svg',
    gallery: ['/seed-images/boat-shallow-anchor.svg', '/seed-images/electronics-sonar.svg'],
    aiNotes: 'Motor hour log downloaded and uploaded to provenance entry.',
    price: 4699,
  },
  {
    brand: 'Power-Pole',
    baseTitle: 'Power-Pole Blade 8 Foot',
    modelName: "Blade 8' Black",
    description:
      'Shallow water anchor with C-Monster 2.0 control, hydraulic pump, and wireless foot switches.',
    tackleCategory: TackleCategory.BOAT_AND_MARINE_ACCESSORY,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Universal'],
    techniqueTags: ['Boat Control', 'Shallow Water'],
    seasonalUse: ['All'],
    shippingProfileKey: 'boat-crate',
    featuredAsset: '/seed-images/boat-shallow-anchor.svg',
    gallery: ['/seed-images/boat-shallow-anchor.svg', '/seed-images/electronics-sonar.svg'],
    aiNotes: 'Hydraulic seals pressure tested prior to listing approval.',
    price: 1999,
  },
  {
    brand: 'Simms',
    baseTitle: 'Simms ProDry Fishing Jacket',
    modelName: 'ProDry Jacket Gunmetal XL',
    description:
      'Three-layer Gore-Tex Pro membrane jacket built for tournament rain days with dual chest pockets.',
    tackleCategory: TackleCategory.APPAREL,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Universal'],
    techniqueTags: ['Rain Gear'],
    seasonalUse: ['Fall', 'Spring'],
    shippingProfileKey: 'apparel-mailer',
    featuredAsset: '/seed-images/apparel-rain-jacket.svg',
    gallery: ['/seed-images/apparel-rain-jacket.svg', '/seed-images/storage-tackle-tray.svg'],
    aiNotes: 'Factory seam tape inspection results uploaded to provenance.',
    price: 599,
  },
  {
    brand: 'Huk',
    baseTitle: 'Huk Tournament Bib',
    modelName: 'Tournament Bib Black L',
    description:
      'Waterproof breathable bib with reflective logos and articulated knees for all-day comfort on deck.',
    tackleCategory: TackleCategory.APPAREL,
    waterType: WaterType.FRESHWATER,
    targetSpecies: ['Universal'],
    techniqueTags: ['Rain Gear'],
    seasonalUse: ['Spring', 'Fall'],
    shippingProfileKey: 'apparel-mailer',
    featuredAsset: '/seed-images/apparel-rain-jacket.svg',
    gallery: ['/seed-images/apparel-rain-jacket.svg', '/seed-images/storage-tackle-tray.svg'],
    aiNotes: 'Moisture barrier test results appended to provenance note.',
    price: 249,
  },
];

export function buildCatalog(): ListingSeedInput[] {
  return BASE_PRODUCTS;
}

export function getVariants(): ListingSeedVariant[] {
  return VARIANTS;
}
