export type ShippingProfileTemplate = {
  key: string;
  label: string;
  courierPreference: string;
  serviceLevel: string;
  packageType: string;
  weightOz: number;
  lengthIn: number;
  widthIn: number;
  heightIn: number;
  insuranceAmountCents: number;
  signatureRequired: boolean;
  handlingNotes: string;
};

export const SHIPPING_TEMPLATES: ShippingProfileTemplate[] = [
  {
    key: 'rod-tube',
    label: 'Carbon rod tube',
    courierPreference: 'UPS',
    serviceLevel: 'Ground',
    packageType: 'Rod Tube',
    weightOz: 48,
    lengthIn: 90,
    widthIn: 5,
    heightIn: 5,
    insuranceAmountCents: 45000,
    signatureRequired: true,
    handlingNotes: 'Foam inserts on both ends with nylon straps. Include provenance photos.',
  },
  {
    key: 'reel-box',
    label: 'Reel vault box',
    courierPreference: 'USPS',
    serviceLevel: 'Priority',
    packageType: 'Reel Box',
    weightOz: 32,
    lengthIn: 14,
    widthIn: 10,
    heightIn: 8,
    insuranceAmountCents: 25000,
    signatureRequired: true,
    handlingNotes: 'Double boxed with foam cradle and silica packet for corrosion control.',
  },
  {
    key: 'combo-case',
    label: 'Combo hard case',
    courierPreference: 'FedEx',
    serviceLevel: 'Two-Day',
    packageType: 'Combo Hard Case',
    weightOz: 96,
    lengthIn: 96,
    widthIn: 8,
    heightIn: 6,
    insuranceAmountCents: 52000,
    signatureRequired: true,
    handlingNotes: 'Secure reel handles and include AI provenance slip with QR.',
  },
  {
    key: 'lure-mailer',
    label: 'Lure armor mailer',
    courierPreference: 'USPS',
    serviceLevel: 'First-Class',
    packageType: 'Bubble Mailer',
    weightOz: 8,
    lengthIn: 10,
    widthIn: 6,
    heightIn: 2,
    insuranceAmountCents: 5000,
    signatureRequired: false,
    handlingNotes: 'Add tamper seal and humidity guard inside carton.',
  },
  {
    key: 'line-spool',
    label: 'Line spool pack',
    courierPreference: 'USPS',
    serviceLevel: 'Priority',
    packageType: 'Small Box',
    weightOz: 12,
    lengthIn: 8,
    widthIn: 8,
    heightIn: 6,
    insuranceAmountCents: 10000,
    signatureRequired: false,
    handlingNotes: 'Include lot number sticker visible through packaging window.',
  },
  {
    key: 'terminal-mailer',
    label: 'Terminal tackle vault',
    courierPreference: 'USPS',
    serviceLevel: 'First-Class',
    packageType: 'Rigid Mailer',
    weightOz: 6,
    lengthIn: 9,
    widthIn: 6,
    heightIn: 1,
    insuranceAmountCents: 4000,
    signatureRequired: false,
    handlingNotes: 'Insert foam pad to immobilize hooks and store provenance note.',
  },
  {
    key: 'electronics-case',
    label: 'Electronics pelican case',
    courierPreference: 'FedEx',
    serviceLevel: 'Express Saver',
    packageType: 'Pelican Case',
    weightOz: 320,
    lengthIn: 28,
    widthIn: 20,
    heightIn: 18,
    insuranceAmountCents: 250000,
    signatureRequired: true,
    handlingNotes: 'Shock sensors armed. Photograph serials before closing case.',
  },
  {
    key: 'storage-mailer',
    label: 'Storage locker carton',
    courierPreference: 'UPS',
    serviceLevel: 'Ground',
    packageType: 'Corrugated Carton',
    weightOz: 80,
    lengthIn: 22,
    widthIn: 16,
    heightIn: 14,
    insuranceAmountCents: 60000,
    signatureRequired: false,
    handlingNotes: 'Add void fill and include desiccant pouch for storage systems.',
  },
  {
    key: 'boat-crate',
    label: 'Marine accessory crate',
    courierPreference: 'FedEx Freight',
    serviceLevel: 'Freight',
    packageType: 'Pallet Crate',
    weightOz: 1200,
    lengthIn: 60,
    widthIn: 24,
    heightIn: 20,
    insuranceAmountCents: 420000,
    signatureRequired: true,
    handlingNotes: 'Strap to pallet and attach compliance pouch with inspection form.',
  },
  {
    key: 'apparel-mailer',
    label: 'Apparel garment mailer',
    courierPreference: 'USPS',
    serviceLevel: 'Priority',
    packageType: 'Soft Mailer',
    weightOz: 24,
    lengthIn: 16,
    widthIn: 12,
    heightIn: 4,
    insuranceAmountCents: 20000,
    signatureRequired: false,
    handlingNotes: 'Fold garments with branded tissue and insert AI provenance card.',
  },
];
